export const variables = {
  HEADERS: {
    vpc_cidr: '10.200.0.0/16',
    vpc_name: 'prod-amplify-vpc',
    pub_sub1_cidr: '10.200.1.0/24',
    pub_sub1_name: 'prod-amplify-pub-sub1',
    pub_sub2_cidr: '10.200.2.0/24',
    pub_sub2_name: 'prod-amplify-pub-sub2',
    pvt_sub1_cidr: '10.200.3.0/24',
    pvt_sub1_name: 'prod-amplify-pvt-sub1',
    pvt_sub2_cidr: '10.200.4.0/24',
    pvt_sub2_name: 'prod-amplify-pvt-sub2',
    igw_name: 'prod-amplify-igw',
    ngw_name: 'prod-amplify-ngw',
    jump_sg_name: 'prod-jump-sg',
    lb_sg_name: 'amplify-prod-alb-SG',
    runner_sg_name: 'prod-RUNNER-SG',
    rds_sg_name: 'prod-amplify-rds-SG',
    public_rt: 'prod-amplify-pub-rt',
    pvt_rt: 'prod-amplify-pvt-rt',
    eip_name: 'prod-amplify-eip',
    dbsubnetgp_name: 'prod-amplify-dbsubnetgp',
    cluster_idententifier: 'prod-amplify-cluster',
    rds_engine: 'aurora-postgresql',
    rds_engine_ver: '11.9',
    rds_dbname: 'prodnetworkDB',
    db_instance_class: 'db.t3.medium',
    dbinstance_name: 'prod-amplify-aurora-instance',
    domain_name: '*.amplifymd.com',
    key_pair: 'amplify-prod',
    ami: 'ami-0e472ba40eb589f49',
  },
}

