export const variables = {
  HEADERS: {
    vpc_cidr: '10.200.0.0/16',
    vpc_name: 'new-amplify-vpc',
    pub_sub1_cidr: '10.200.1.0/24',
    pub_sub1_name: 'new-amplify-pub-sub1',
    pub_sub2_cidr: '10.200.2.0/24',
    pub_sub2_name: 'new-amplify-pub-sub2',
    pvt_sub1_cidr: '10.200.3.0/24',
    pvt_sub1_name: 'new-amplify-pvt-sub1',
    pvt_sub2_cidr: '10.200.4.0/24',
    pvt_sub2_name: 'new-amplify-pvt-sub2',
    igw_name: 'new-amplify-igw',
    ngw_name: 'new-amplify-ngw',
    jump_sg_name: 'new-jump-sg',
    lb_sg_name: 'new-amplify-stage-alb-SG',
    runner_sg_name: 'new-RUNNER-SG',
    rds_sg_name: 'new-amplify-rds-SG',
    public_rt: 'new-amplify-pub-rt',
    pvt_rt: 'new-amplify-pvt-rt',
    eip_name: 'new-amplify-eip',
    dbsubnetgp_name: 'new-amplify-dbsubnetgp',
    cluster_idententifier: 'new-amplify-cluster',
    rds_engine: 'aurora-postgresql',
    rds_engine_ver: '11.9',
    rds_dbname: 'newamplifyDB',
    db_instance_class: 'db.t3.medium',
    dbinstance_name: 'new-amplify-aurora-instance',
    domain_name: '*.amplifymd.com',
    new_domain_name: '*.stage.amplifymd.com',
    key_pair: 'amplify-runner',
    ami: 'ami-0e472ba40eb589f49',
  },
}

