name: testing calling variables and secrets

on:
  push:
    branches:
      - main
      - test-resuability

jobs:
  test-vars:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name == 'main' && 'test' || github.ref_name == 'test-resuability' && 'reuse' || github.ref_name == 'stage' && 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: printing env and repo vars
        run: |
          echo environment_var="${{ vars.ENV_VARS }}"
          echo repo_var="${{ vars.REPO_VARS }}"
          echo repo_secret="${{ secrets.REPO_SECRET }}"
          echo env_secretr="${{ secrets.ENV_SECRET }}"

  test:
    runs-on: ubuntu-latest
    needs: test-vars
    environment: ${{ github.ref_name == 'main' && 'test' || github.ref_name == 'test-resuability' && 'reuse' || github.ref_name == 'stage' && 'staging' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: printing env and repo vars
        run: |
          echo repo_var="${{ vars.REPO_VARS }}"
          echo repo_secret="${{ secrets.REPO_SECRET }}"
          echo env_secretr="${{ secrets.ENV_SECRET }}"
